### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by zouguojian** [ibalazevic/HypER#9]
Traceback (most recent call last):
  File "/Users/guojianzou/Downloads/HypER-master/HypER/hyper.py", line 196, in <module>
    experiment.train_and_eval()
  File "/Users/guojianzou/Downloads/HypER-master/HypER/hyper.py", line 167, in train_and_eval
    self.evaluate(model, d.valid_data)
  File "/Users/guojianzou/Downloads/HypER-master/HypER/hyper.py", line 89, in evaluate
    rank = np.where(sort_idxs[j]==e2_idx[j])[0][0]
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by meredith92** [comment]
same problem? have been solved?

**Comment by TestBody404** [comment]
Has anyone solved it？

**Comment by TestBody404** [comment]
Probably solved,change the code to `rank= np.where(sort_idxs[j]==e2_idx[j].item())[0][0]` if the pytorch version is greater than 1.0

**Comment by 5zongyuan** [comment]
> Probably solved,change the code to `rank= np.where(sort_idxs[j]==e2_idx[j].item())[0][0]` if the pytorch version is greater than 1.0

That's good! Thanks!
